"""
Multi-dataset, identity-aware train/val/test splitting.

Reads data/metadata/metadata.csv (the single source of truth generated by
src/data/metadata.py across every enabled dataset) and writes:

    data/splits/train.csv
    data/splits/val.csv
    data/splits/test.csv

each with columns: video_path, dataset, identity, label

Identity handling
------------------
A row's "identity" field may contain MULTIPLE comma-separated tokens (e.g.
a Celeb-DF fake video references both a source and target identity:
"id0,id1"). Two videos that share ANY token must end up in the same split --
otherwise a face seen in training can reappear in test via a different
video, which is exactly the leakage problem flagged in the original repo
review. This is solved with a union-find over tokens: any two rows sharing
a token get merged into one group, transitively, and splitting happens at
the GROUP level, never the individual video level.

Rows with no identity information (identity is empty/NaN -- the documented
fallback for datasets that don't provide it, e.g. custom videos without a
"<identity>__" filename prefix) are each their own singleton group, which
is equivalent to a plain video-level split for exactly those rows.

Stratification
---------------
sklearn's StratifiedGroupKFold is used so real/fake class balance is
preserved in each split (approximately -- exact stratification isn't always
achievable when group sizes are uneven, which is expected and fine).
"""

import os

import pandas as pd
from sklearn.model_selection import StratifiedGroupKFold

METADATA_PATH = "data/metadata/metadata.csv"
SPLITS_DIR = "data/splits"

SEED = 42
TEST_FRACTION = 0.10
VAL_FRACTION = 0.10  # of the ORIGINAL total, not of the remainder


class _UnionFind:
    def __init__(self):
        self.parent = {}

    def find(self, x):
        self.parent.setdefault(x, x)
        while self.parent[x] != x:
            self.parent[x] = self.parent[self.parent[x]]
            x = self.parent[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[ra] = rb


def _assign_groups(df):
    """
    Returns a Series of group IDs, one per row, such that any two rows
    sharing an identity token end up with the same group ID.
    """
    uf = _UnionFind()
    row_tokens = []

    for idx, identity in df["identity"].items():
        if pd.isna(identity) or str(identity).strip() == "":
            tokens = [f"__singleton__{idx}"]  # unique to this row -> its own group
        else:
            tokens = [t.strip() for t in str(identity).split(",") if t.strip()]
        row_tokens.append(tokens)
        for t in tokens[1:]:
            uf.union(tokens[0], t)

    groups = []
    for tokens in row_tokens:
        groups.append(uf.find(tokens[0]))

    return pd.Series(groups, index=df.index)


def _stratified_group_split(df, group_col, label_col, test_fraction, val_fraction, seed):
    """
    Two-stage StratifiedGroupKFold: first carve off the test set, then split
    the remainder into train/val. Returns (train_df, val_df, test_df).
    """
    n_splits_test = max(2, round(1 / test_fraction))
    skf_test = StratifiedGroupKFold(n_splits=n_splits_test, shuffle=True, random_state=seed)

    trainval_idx, test_idx = next(
        skf_test.split(df, df[label_col], groups=df[group_col])
    )
    trainval_df = df.iloc[trainval_idx]
    test_df = df.iloc[test_idx]

    # val_fraction is expressed relative to the ORIGINAL total; convert to
    # a fraction of the remaining trainval pool.
    remaining_fraction = 1 - (len(test_df) / len(df))
    val_fraction_of_remainder = min(0.5, (val_fraction / remaining_fraction)) if remaining_fraction > 0 else 0.5
    n_splits_val = max(2, round(1 / val_fraction_of_remainder))

    skf_val = StratifiedGroupKFold(n_splits=n_splits_val, shuffle=True, random_state=seed)
    train_idx, val_idx = next(
        skf_val.split(trainval_df, trainval_df[label_col], groups=trainval_df[group_col])
    )
    train_df = trainval_df.iloc[train_idx]
    val_df = trainval_df.iloc[val_idx]

    return train_df, val_df, test_df


def create_splits(metadata_path=METADATA_PATH, splits_dir=SPLITS_DIR):
    if not os.path.exists(metadata_path):
        raise FileNotFoundError(
            f"Metadata not found at {metadata_path}. Run "
            f"`python -m src.data.metadata` first to generate it."
        )

    df = pd.read_csv(metadata_path)

    if len(df) == 0:
        raise RuntimeError(
            f"{metadata_path} is empty -- no enabled dataset produced any "
            f"videos. Check config.yaml's `datasets` section and confirm "
            f"at least one dataset's raw videos are actually present."
        )

    df["_group"] = _assign_groups(df)

    train_df, val_df, test_df = _stratified_group_split(
        df, group_col="_group", label_col="label",
        test_fraction=TEST_FRACTION, val_fraction=VAL_FRACTION, seed=SEED,
    )

    # Sanity check: no group should ever appear in more than one split.
    train_groups = set(train_df["_group"])
    val_groups = set(val_df["_group"])
    test_groups = set(test_df["_group"])
    overlap = (train_groups & val_groups) | (train_groups & test_groups) | (val_groups & test_groups)
    if overlap:
        raise RuntimeError(
            f"Identity leakage detected across splits ({len(overlap)} "
            f"overlapping group(s)) -- this should be impossible with "
            f"StratifiedGroupKFold and indicates a bug. Not writing CSVs."
        )

    output_cols = ["video_path", "dataset", "identity", "label"]
    os.makedirs(splits_dir, exist_ok=True)

    train_df[output_cols].to_csv(os.path.join(splits_dir, "train.csv"), index=False)
    val_df[output_cols].to_csv(os.path.join(splits_dir, "val.csv"), index=False)
    test_df[output_cols].to_csv(os.path.join(splits_dir, "test.csv"), index=False)

    print("Splits created successfully (identity-aware, multi-dataset).")
    print(f"Train: {len(train_df)}  (groups: {len(train_groups)})")
    print(f"Val:   {len(val_df)}  (groups: {len(val_groups)})")
    print(f"Test:  {len(test_df)}  (groups: {len(test_groups)})")
    print("\nPer-dataset breakdown:")
    for split_name, split_df in (("train", train_df), ("val", val_df), ("test", test_df)):
        counts = split_df["dataset"].value_counts().to_dict()
        print(f"  {split_name}: {counts}")


if __name__ == "__main__":
    create_splits()
